name: Post New Politiet Updates

permissions:
  contents: read

on:
  schedule:
    # Run every 30 minutes.
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  post-new-politiet-updates:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Post new updates
        env:
          BLUESKY_POLUP_ALL_PASSWORD: ${{ secrets.BLUESKY_POLUP_ALL_PASSWORD }}
          BLUESKY_POLUP_ALL_USERNAME: ${{ secrets.BLUESKY_POLUP_ALL_USERNAME }}
          OPEN_ROUTER_API_KEY: ${{ secrets.OPEN_ROUTER_API_KEY }}
        run: yarn run post-new-politiet-updates
